export const ROOM_LIST = [
    "B2 - B2 - LAB INTEGRASI",
    "B2 - R1",
    "B3 - R1",
    "B3 - R2",
    "B3 - R3",
    "CM - 101",
    "CM - 102",
    "CM - 103",
    "CM - 201",
    "CM - 202",
    "CM - 203",
    "CM - 204",
    "CM - 205",
    "CM - 206 (LAB MULTIMEDIA 2)",
    "CM - 207 (LAB MULTIMEDIA 1)",
    "CM - 208",
    "CM - AUDITORIUM",
    "CM - LAB 3 (301)",
    "G1 - HALAMAN PARKIR BELAKANG",
    "G1 - RUANG RAPAT (EX SSC)",
    "G1 - RUANG TAMU",
    "G1 - MASJID ROUDLOTUL ILMI",
    "G2 - R2",
    "G2 - R3",
    "G2 - R4",
    "G2 - R5",
    "G2 - R6",
    "G2 - R7",
    "G2 - RUANG KESEHATAN",
    "G3 - HALAMAN",
    "G3 - R1",
    "G3 - R2",
    "G3 - R3 (R. DISKUSI)",
    "G3 - R4",
    "G3 - RUANG TRANSIT",
    "G4 - R1",
    "G4 - R2",
    "G4 - R3",
    "G4 - R4",
    "G4 - RUANG TRANSIT",
    "G5 - LAB 1 (PEMROGRAMAN)",
    "G5 - LAB 2 (ERP)",
    "G5 - LAB AUDIO VISUAL",
    "G5 - LAB FEB",
    "G5 - RUANG STARTUP CORNER",
    "G5 - STUDIO INFORMATION AND COMMUNICATION TECHNOLOGY",
    "KAMPUS B - LOBBY INT. 1 BARAT",
    "KAMPUS B - LOBBY INT. 1 SELATAN",
    "KAMPUS B - LOBBY INT. 1 TIMUR",
    "KAMPUS B - LOBBY INT. 1 UTARA",
    "KAMPUS B - LOBBY INT. 2 BARAT",
    "KAMPUS B - LOBBY INT. 2 TIMUR",
    "KAMPUS B - ROOFTOP INT. 3",
    "KAMPUS B - RUANG TRANSIT INT. 2",
    "KAMPUS C - C101",
    "KAMPUS C - C102",
    "KAMPUS C - LAB PROSES",
    "KAMPUS C - LABORATORIUM RISET TEKNOLOGI ARGOINDUSTRI",
    "KAMPUS C - MUSHOLLA",
    "KAMPUS C - RUANG TRANSIT DOSEN",
    "PPS - LAB ANALISA BAHAN",
    "PPS - LAB FUNDAMENTAL",
    "TRANSPORTASI - TOYOTA HIACE (W 7215 AF)",
    "TRANSPORTASI - TOYOTA INNOVA (W 1678 L)",
]

export const OPERATIONAL_HOURS = [
    "07:00", "08:00", "09:00", "10:00", "11:00", "12:00",
    "13:00", "14:00", "15:00", "16:00", "17:00"
]
